default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch("PGHOST", "localhost") %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: invoicer_development
  host: localhost

test:
  <<: *default
  database: <%= ENV["PG_DATABASE"] || "invoicer_test" %>
  username: <%= ENV["PG_USERNAME"] || "postgres" %>
  password: <%= ENV["PG_PASSWORD"] || "postgres" %>
  host: <%= ENV["PG_HOST"] || "localhost" %>

production:
  <<: *default
  database: invoicer_production
  username: <%= ENV["PGUSER"] %>
  password: <%= ENV["PGPASSWORD"] %>
